version: 2
jobs:
  build:
    docker:
      - image: node
    steps:
      - run:
          name: Setup
          command: |
            apt -y update --fix-missing
            apt -y upgrade
            npm install --global codecov
      - checkout
      - run:
          name: Dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: |
            npm run test
            codecov
